# Generated by Django 5.0.14 on 2025-12-17 00:02

import base.models.class_time
import base.models.day_not_available
import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('symbology', models.PositiveIntegerField(blank=True, unique=True, verbose_name='simbología')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Formato: YYYY-YYYY', max_length=9, unique=True, verbose_name='Nombre del curso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre completo')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('course_type', models.CharField(choices=[('CD', 'Curso Diurno'), ('CE', 'Curso por Encuentro')], default='CD', max_length=5, verbose_name='tipo de curso')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.faculty', verbose_name='facultad')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='nombre')),
                ('start', models.DateField(default=datetime.date(2025, 9, 1), verbose_name='inicio')),
                ('end', models.DateField(default=datetime.date(2026, 6, 30), verbose_name='fin')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.course', verbose_name='curso')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DayNotAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=80, verbose_name='motivo')),
                ('day', models.DateField(default=base.models.day_not_available.DayNotAvailable.day_default, verbose_name='día')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.period', verbose_name='período')),
            ],
            options={
                'verbose_name': 'Día no disponible',
                'verbose_name_plural': 'Días no disponibles',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('group', models.CharField(max_length=50, verbose_name='grupo')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.career', verbose_name='carrera')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.classroom', verbose_name='aula')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.period', verbose_name='período')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ('period',),
            },
        ),
        migrations.CreateModel(
            name='LoadBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.JSONField(blank=True, default=list, verbose_name='Balance')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.schedule', verbose_name='horario')),
            ],
            options={
                'verbose_name': 'Balance de Carga',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('symbology', models.CharField(max_length=4, verbose_name='simbología')),
                ('hours_found', models.PositiveIntegerField(verbose_name='fondo de horas')),
                ('type', models.CharField(choices=[('simple', 'Simple'), ('optativa', 'Optativa'), ('electiva', 'Electiva')], default='simple', max_length=10, verbose_name='tipo')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.career', verbose_name='carrera')),
                ('teachers', models.ManyToManyField(blank=True, to='base.teacher', verbose_name='profesor(es)')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='subjects',
            field=models.ManyToManyField(to='base.subject', verbose_name='asignaturas'),
        ),
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=base.models.class_time.ClassTime.day_default, verbose_name='día')),
                ('number', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1, message='El número mínimo del turno es 1'), django.core.validators.MaxValueValidator(limit_value=6, message='El número máximo del turno es 6')], verbose_name='número')),
                ('activities', models.ManyToManyField(blank=True, help_text='Varias actividades pueden asociarse a un turno, ej: Seminario y Evaluación', to='base.activity', verbose_name='actividades')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.schedule', verbose_name='horario')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subject', verbose_name='asignatura')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.teacher', verbose_name='profesor')),
            ],
            options={
                'verbose_name': 'Turno de Clase',
                'verbose_name_plural': 'Turnos de Clases',
            },
        ),
        migrations.CreateModel(
            name='WeekNotAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=80, verbose_name='motivo')),
                ('start_date', models.DateField(help_text='Fecha de inicio del rango no disponible', verbose_name='fecha de inicio')),
                ('end_date', models.DateField(help_text='Fecha de fin del rango no disponible', verbose_name='fecha de fin')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.period', verbose_name='período')),
            ],
            options={
                'verbose_name': 'Semana no Disponible',
                'verbose_name_plural': 'Semanas no Disponibles',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(choices=[(1, 'Primer año'), (2, 'Segundo año'), (3, 'Tercer año'), (4, 'Cuarto año'), (5, 'Quinto año')], default=1, verbose_name='número')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.career', verbose_name='carrera')),
            ],
            options={
                'verbose_name': 'Año',
                'verbose_name_plural': 'Años',
                'ordering': ('number',),
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.year', verbose_name='año'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.year', verbose_name='año'),
        ),
        migrations.AddConstraint(
            model_name='career',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_career'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('name', 'course'), name='unique_course'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.CheckConstraint(check=models.Q(('start__week_day', 1), _negated=True), name='check_start_period_not_sunday', violation_error_message='La fecha de inicio no puede ser domingo'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.CheckConstraint(check=models.Q(('end__week_day', 1), _negated=True), name='check_end_period_not_sunday', violation_error_message='La fecha de fin no puede ser domingo'),
        ),
        migrations.AddConstraint(
            model_name='daynotavailable',
            constraint=models.UniqueConstraint(fields=('day', 'period'), name='unique_day_not_available'),
        ),
        migrations.AddConstraint(
            model_name='daynotavailable',
            constraint=models.CheckConstraint(check=models.Q(('day__week_day', 1), _negated=True), name='check_day_not_available_not_sunday', violation_error_message='El día no puede ser domingo'),
        ),
        migrations.AddConstraint(
            model_name='classtime',
            constraint=models.UniqueConstraint(fields=('day', 'number', 'schedule'), name='unique_classtime'),
        ),
        migrations.AddConstraint(
            model_name='classtime',
            constraint=models.CheckConstraint(check=models.Q(('day__week_day', 1), _negated=True), name='check_day_not_sunday', violation_error_message='El día no puede ser domingo'),
        ),
        migrations.AddConstraint(
            model_name='weeknotavailable',
            constraint=models.UniqueConstraint(fields=('start_date', 'end_date', 'period'), name='unique_week_not_available'),
        ),
        migrations.AddConstraint(
            model_name='year',
            constraint=models.UniqueConstraint(fields=('number', 'career'), name='unique_year'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('name', 'career', 'year'), name='unique_subject'),
        ),
    ]
