# Generated by Django 5.1.4 on 2025-06-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='year',
            name='unique_year',
        ),
        migrations.RemoveField(
            model_name='year',
            name='course',
        ),
        migrations.AddConstraint(
            model_name='year',
            constraint=models.UniqueConstraint(fields=('number', 'career'), name='unique_year'),
        ),
    ]
