# Generated by Django 5.1.4 on 2025-06-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_year_unique_year_remove_year_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtime',
            name='activities',
        ),
        migrations.AddField(
            model_name='classtime',
            name='activities',
            field=models.ManyToManyField(blank=True, help_text='Varias actividades pueden asociarse a un turno, ej: Seminario y Evaluación', to='base.activity', verbose_name='actividades'),
        ),
    ]
