# Generated by Django 5.1.4 on 2025-06-16 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_classtime_activities_classtime_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='grupo'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='class_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.classroom', verbose_name='aula'),
        ),
    ]
