# Generated by Django 5.1.4 on 2025-06-16 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_classroom_schedule_group_schedule_class_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='class_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.classroom', verbose_name='aula'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.CharField(default=1, max_length=50, verbose_name='grupo'),
            preserve_default=False,
        ),
    ]
